services:
  seq:
    image: "datalust/seq:latest"
    ports:
      - "8082:80"
      - "5341:5341"
      - "45341:45341"
    environment:
      ACCEPT_EULA: Y
    volumes:
      - vol_seq:/data
  
  zipkin-storage:
    image: openzipkin/zipkin-cassandra
    container_name: zipkin-cassandra
    ports:
      - "9042:9042"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx2g -XX:+ExitOnOutOfMemoryError
    volumes:
      - vol_zipkin:/cassandra/data

  zipkin:
    image: "openzipkin/zipkin:latest"
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_ENSURE_SCHEMA=false
      - CASSANDRA_CONTACT_POINTS=zipkin-cassandra
      - JAVA_OPTS=-Xms256m -Xmx2g -XX:+ExitOnOutOfMemoryError
    depends_on:
      - zipkin-storage

volumes:
  vol_zipkin:
  vol_seq:
